### ISSUE TITLE
README.md 里面的有些链接还没改。。。

### ISSUE THREAD

**Issue by myrshfrs** [SoDa-GitHub/SSD-Windows#1]

**Comment by SoDa-GitHub** [comment]
正式版还没发布，repo还在调整，我TM当然知道readme.md里还有东西没改，你当我是神仙？一瞬间搞完所有工作？老子大半夜到现在还在完善这个project，需要你废话来提醒我readme.md没改吗？轮到改readme.me的时候自然会改
